# Generated by Django 4.0 on 2022-01-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_alter_book_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_bestseller',
            new_name='bestseller',
        ),
    ]
